### ISSUE TITLE
Saving session and loading session

### ISSUE THREAD

**Issue by konsolerr** [ctlab/phantasus#47]
So I would like to save the session with this fancy anchor button, but I couldn't find a way to load it back.
So how do I load a session from JSON-file on my hard drive?

![image](https://user-images.githubusercontent.com/2555859/28579071-330f3d12-7164-11e7-9a1c-195bdf53ff5f.png)

**Comment by baba-beda** [comment]
Use the Open Button (Ctrl+O), then choose as Open file action: Open session.
![image](https://user-images.githubusercontent.com/8116929/28579546-9fdc00a0-7165-11e7-8566-45f5dc7b4a2b.png)

After that, choose JSON-file from your hard drive. 

Unfortunately, right now, you can only do it having some heatmap open, but not from the index page. Will be fixed in next versions.

**Comment by assaron** [comment]
At the moment it doesn't seem to be working even with an opened heatmapt
